using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using ToolsQA.Demo;

IWebDriver driver = new ChromeDriver();
driver.Url = "https://demoqa.com/";
Thread.Sleep(1000);
driver.Manage().Window.Maximize();
Thread.Sleep(1000);
Thread.Sleep(1000);
IJavaScriptExecutor js = (IJavaScriptExecutor)driver;
js.ExecuteScript("window.scrollTo(0, document.body.scrollHeight)");
driver.FindElement(By.CssSelector("#app > div > div > div.home-body > div > div:nth-child(6)")).Click();
Thread.Sleep(1000);
js.ExecuteScript("window.scrollTo(0, document.body.scrollHeight)");
Thread.Sleep(1000);
var item = driver.FindElement(By.ClassName("show"));
item.FindElement(By.Id("item-0")).Click();
Thread.Sleep(1000);
driver.LoginToBookStore();
Thread.Sleep(1000);
driver.DeleteFromCollection();
Thread.Sleep(1000);
js.ExecuteScript("window.scrollTo(0, document.body.scrollHeight)");
driver.AddToCollection();
Thread.Sleep(1000);
js.ExecuteScript("window.scrollTo(0, document.body.scrollHeight)");
var item2 = driver.FindElement(By.ClassName("show"));
item2.FindElement(By.Id("item-3")).Click();
Thread.Sleep(1000);
js.ExecuteScript("window.scrollTo(0, document.body.scrollHeight)");
Thread.Sleep(1000);
js.ExecuteScript("window.scrollTo(0, 0)");
Thread.Sleep(1000);
driver.LogoutFromBookStore();
Thread.Sleep(10000);
driver.Close();
driver.Quit();
